// <auto-generated />
using System;
using API_projet_parc_informatique.BD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_projet_parc_informatique.Migrations
{
    [DbContext(typeof(ParcInfoBdContext))]
    [Migration("20250327113706_DataBase")]
    partial class DataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("API_projet_parc_informatique.Models.Parc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Parcs");
                });

            modelBuilder.Entity("API_projet_parc_informatique.Models.Poste", b =>
                {
                    b.Property<int>("Id_poste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresseIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdresseMac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisqueDur")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_salle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Processeur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ram")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemeExploitation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_poste");

                    b.HasIndex("Id_salle");

                    b.ToTable("Postes");
                });

            modelBuilder.Entity("API_projet_parc_informatique.Models.Remontees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CPU")
                        .HasColumnType("REAL");

                    b.Property<string>("ConnectiviteReseau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRemontee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DisqueDur")
                        .HasColumnType("REAL");

                    b.Property<string>("EtatSysteme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_poste")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RAM")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Id_poste");

                    b.ToTable("Remontees");
                });

            modelBuilder.Entity("API_projet_parc_informatique.Models.Salle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_parc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id_parc");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("API_projet_parc_informatique.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date_creation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_poste")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_user")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priorite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id_poste");

                    b.HasIndex("Id_user");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("API_projet_parc_informatique.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API_projet_parc_informatique.Models.Poste", b =>
                {
                    b.HasOne("API_projet_parc_informatique.Models.Salle", "Salle")
                        .WithMany("Postes")
                        .HasForeignKey("Id_salle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("API_projet_parc_informatique.Models.Remontees", b =>
                {
                    b.HasOne("API_projet_parc_informatique.Models.Poste", "Poste")
                        .WithMany("Remontees")
                        .HasForeignKey("Id_poste")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poste");
                });

            modelBuilder.Entity("API_projet_parc_informatique.Models.Salle", b =>
                {
                    b.HasOne("API_projet_parc_informatique.Models.Parc", "Parc")
                        .WithMany("Salles")
                        .HasForeignKey("Id_parc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parc");
                });

            modelBuilder.Entity("API_projet_parc_informatique.Models.Ticket", b =>
                {
                    b.HasOne("API_projet_parc_informatique.Models.Poste", "Poste")
                        .WithMany("Tickets")
                        .HasForeignKey("Id_poste")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_projet_parc_informatique.Models.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("Id_user")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Poste");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API_projet_parc_informatique.Models.Parc", b =>
                {
                    b.Navigation("Salles");
                });

            modelBuilder.Entity("API_projet_parc_informatique.Models.Poste", b =>
                {
                    b.Navigation("Remontees");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("API_projet_parc_informatique.Models.Salle", b =>
                {
                    b.Navigation("Postes");
                });

            modelBuilder.Entity("API_projet_parc_informatique.Models.User", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
